name: Examples

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:

  # This runs JavaScript tests using the Mocha test framework
  javascript-mocha:
    name: JavaScript / Mocha
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Build and test
        run: |
          npm ci
          npm run test
        working-directory: javascript-mocha
      - name: Show XML
        run: cat javascript-mocha/results/**/*.xml
        if: always()
      - name: Create test summary
        uses: test-summary/action@v1
        with:
          paths: javascript-mocha/results/**/*.xml
          show: all
        if: always()
